name: Deploy EC2 
 
on:
  push:
    branches: [main]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: actions/aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ASIASFL3AHUUV3PGITMN }}
          aws-secret-access-key: ${{ secrets.ypKmvbLoOpRlH5ZVz5G/UoHh+Xf5IjkrES6XNAue }}
          region: us-east-1
 
      - name: Terraform Init
        run: terraform init
 
      - name: Terraform Plan
        run: terraform plan
 
      - name: Terraform Apply
        run: terraform apply
